### PR TITLE
Add authentication using arguments from OneSix wrapper

### PR DESCRIPTION
**Pull request by MrMelon54**
MultiMC and PolyMC support

Adds a wrapper to the fishing bot so it accepts the username, profile id and access token from 3rd party launchers using the vanilla Minecraft command line arguments.

### CODE REVIEW

**Comment by MrMelon54** [comment]
I'm gonna refactor this to make the quality better lol

**Comment by MrMelon54** [comment]
You should also add information on how to install it like this to the readme.

Open MultiMC/PolyMC, pick an instance and click "edit instance", open the "version" page, click "replace minecraft.jar", choose the built fishing bot jar.

Now you can launch the instance and load the fishing bot instead of a minecraft client

**Comment by MrKinau** [comment]
Indeed the simple label is much more intuitive.
Thanks for your PR. I will add information on how to use OneSix to the Wiki (which is linked by the README) and to my Discord server and then publish a new version.

**Comment by MrMelon54** [comment]
awesome

**Pull request merged**
